name: Build and Deploy to Firebase Preview
on: pull_request
permissions:
  checks: write
  contents: read
  pull-requests: write
jobs:
  Build-and-Deploy:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Download Experience Builder
        run: curl -o exb.zip "$(curl -s 'https://downloads.arcgis.com/dms/rest/download/secured/arcgis-experience-builder-1.15.zip?f=json&folder=software%2FExperienceBuilder%2F1.15' | python3 -c "import sys, json; print(json.load(sys.stdin)['url'])")"
      - name: Unzip Experience Builder
        run: unzip -q exb.zip -d exb
      # - name: Copy Custom Widgets
      #   run: cp -r widgets/* exb/ArcGISExperienceBuilder/client/your-extensions/widgets
      - name: Copy Custom Themes
        run: cp -r themes/* exb/ArcGISExperienceBuilder/client/your-extensions/themes
      - name: Create App directory
        run: mkdir public && cd public && mkdir apps && cd apps
        working-directory: exb/ArcGISExperienceBuilder/server
      - name: Copy apps
        run: cp -r apps/* exb/ArcGISExperienceBuilder/server/public/apps
      - name: NPM install client folder
        run: npm ci
        working-directory: exb/ArcGISExperienceBuilder/client
      - name: NPM install in server folder
        run: npm ci
        working-directory: exb/ArcGISExperienceBuilder/server
      - name: Build widgets - dev
        run: npm run build:dev
        working-directory: exb/ArcGISExperienceBuilder/client
      - name: Build widgets
        run: npm run build:prod
        working-directory: exb/ArcGISExperienceBuilder/client
      - name: Run download script
        run: node -e "require('./server/src/middlewares/dev/apps/app-download.js').zipApp('8', 'app.zip')"
        working-directory: exb/ArcGISExperienceBuilder
        env:
          NODE_ENV: production
      - name: Unzip app zip
        run: |
          unzip -q app.zip -d app
          chmod -R 777 app
        working-directory: exb/ArcGISExperienceBuilder
      - name: Debug - List app contents
        run: |
          echo "Contents of app directory:"
          ls -la exb/ArcGISExperienceBuilder/app
          echo "Contents of jimu-core:"
          ls -la exb/ArcGISExperienceBuilder/app/jimu-core
          echo "First few lines of init.js:"
          head -n 5 exb/ArcGISExperienceBuilder/app/jimu-core/init.js
          echo "First few lines of index.html:"
          head -n 10 exb/ArcGISExperienceBuilder/app/index.html

      - name: Check file types
        run: |
          echo "File type of init.js:"
          file exb/ArcGISExperienceBuilder/app/jimu-core/init.js
          echo "File type of index.html:"
          file exb/ArcGISExperienceBuilder/app/index.html
      - name: Update paths in index.html
        working-directory: exb/ArcGISExperienceBuilder/app
        run: |
          # Keep base href but modify it
          sed -i 's/<base href="\.\/cdn\/14\/"/<base href="\/"/' index.html
          # Update script paths to absolute
          sed -i 's/src="\.\/jimu-core/src="\/jimu-core/g' index.html
          # Replace BASE_URL placeholder with absolute paths
          sed -i 's|https://BASE_URL/|/|g' index.html
          # Update API URL
          sed -i 's|https://API_URL/|https://js.arcgis.com/4.30/|g' index.html

      - name: Setup import paths
        working-directory: exb/ArcGISExperienceBuilder/app
        run: |
          echo "Updating import paths..."
          find . -type f -name "*.js" -exec sed -i 's/https:\/\/BASE_URL\//\//g' {} +
          find . -type f -name "*.js" -exec sed -i 's/https:\/\/API_URL\//https:\/\/js.arcgis.com\/4.30\//g' {} +
      - name: Deploy to Firebase Preview Channel
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_UT_DNR_UGS_ENERGY_DEV }}
          projectId: ut-dnr-ugs-energy-dev
          channelId: preview
          # entryPoint: exb/ArcGISExperienceBuilder/app
